[board]
name = "esp32"
target = "xtensa-esp32-espidf"
mcuversion = "esp32"
flash_size = "4"

[spi]
sck_pin = 18
miso_pin = 19
mosi_pin = 23

[sd]
cs_pin = 5
spi_clock_hz = 1000000

[rfid]
cs_pin = 22
rst_pin = 21
spi_clock_hz = 1000000